### ISSUE TITLE
Pagination question

### ISSUE THREAD

**Issue by AaronAnz** [mitchhymel/GooglePlayMusicAPI#4]
Is there a way to do pagination with this library? I want to do pagination with albums and artists etc to decrease memory usage in my app but allow an infinite scroll until there are no more available objects.

**Comment by mitchhymel** [comment]
Google's api does have support for pagination and the library uses it (see [here](https://github.com/mitchhymel/GooglePlayMusicAPI/blob/05c1845e3a8e5def62c7fd42a2679e4e3f034209/GooglePlayMusicClient/Client/BaseRequestClient.cs#L55)), but the library doesn't expose that currently - not for any technical reason but mainly because my use case didn't require it. I'll have to look into how much work it'd be to redesign the library api surface to expose pagination.

**Comment by AaronAnz** [comment]
I saw the incremental stuff but no matter what I get a NaN result. So this won't work unless you recode the library?

**Comment by mitchhymel** [comment]
So it looks like Google's api has no concept of pagination for the search endpoint, but it was easy enough to expose the incremental way to fetch the user's library that was already being used behind the scenes (see 699bced652e421a23cf50f51bbfef66d2e991276). Does that work for you?

**Comment by AaronAnz** [comment]
I primarily wanted it for the search. If they don't support it no big deal. I will just use it as is I guess.
